### ISSUE TITLE
Some improvements we may want to make to the code

### ISSUE THREAD

**Issue by RoyStegeman** [NNPDF/nnusf#14]
- [x] Make the name of the fit output folder the same as the name of the runcard instead of "fits"
- [ ] Make code more user-friendly by storing info in `dataclass` objects instead of dicts
- [x] Make a default folder to store the fits, so the path doesn't need to be passed each time plots are made
- [ ] Make a single interface for all plots 
- [ ] Add the option to either use `patience_epochs` or `patience_fraction` to the runcard. Current `stopping_patience`  is in epochs, which is different from `n3fit` where it's a fraction, this might lead to confusion
- [x] add a `generate_pseudodata` boolean flag option to the fit runcard
- [ ] Make names in `callbacks.py` more sensible
- [x] **do feature scaling outside model, this will also affect how models are saves/loaded**
- [ ] Stop `rich` from messing with `ipdb`
- [ ] related to above, just print chi2 info line-by-line so the logs contain a history
- [ ] make gradient descent stochastic to reduce computational costs

**Comment by Radonirinaunimi** [comment]
Closing this as most of the points are no longer applicable.
