### ISSUE TITLE
Computation of GLS sum rules broke due to changes in EKO

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnusf#85]
The computation of the GLS sum rule is now broken due to type change in the `coupling` class of `eko.coupling`. In particular, at some point the `thresholds_ratios` was of type `MatchingScales` now it is a `list`. Since `eko` is not a direct dependency its version depends on `yadism` (which now has to be `v0.12.3`).

**Comment by felixhekhorn** [comment]
Just to say that this specific issue at hand is the result of https://github.com/NNPDF/eko/pull/199

**Comment by Radonirinaunimi** [comment]
> Just to say that this specific issue at hand is the result of [NNPDF/eko#199](https://github.com/NNPDF/eko/pull/199)

Thanks for pointing this out 😃
